version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  user-db:
    image: mysql:8.0
    volumes:
       - user_data: /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD=root_pass
      MYSQL_USER=user
      MYSQL_PASSWORD=password
      MYSQL_DATABASE=findit

  user-service:
    build: ./user-service
    depends_on:
      - user-db
    environment:
      DB_HOST=user-db:3306
      DB_USER=user
      DB_PASSWORD=password

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080"
    environment:
      HTTP_HOST=8080
    volumes:
      - /var/run/docker.sock: /var/run/docker.sock

volumes:
    user_data: