version: '3'

services:
  file-db-dev:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${FILE_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${FILE_MYSQL_USER}
      MYSQL_PASSWORD: ${FILE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${FILE_MYSQL_DATABASE}
    volumes:
      - file_data_dev:/var/lib/mysql

volumes:
  file_data_dev:
