version: '3'

services:
  file-db-dev:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: fileservice
    volumes:
      - file_data_dev:/var/lib/mysql

volumes:
  file_data_dev: